### ISSUE TITLE
Using Python 3.12?

### ISSUE THREAD

**Issue by YogiLiu** [bamboo-cms/bamboo#8]
https://github.com/bamboo-cms/bamboo/blob/791258e2ecb1f18621ddc29ca65f7e3ef767098c/pyproject.toml#L15

Is using Python 3.12 too radical?

**Comment by frostming** [comment]
I don't think so. Unlike a library, for an application it's possible to use a newer version. Because users are able to use our application with docker or via cloud service. The `requires-python` constraint is only meaningful to the developers and contributors. We can draw a line, as a contribution guide, that you MUST use 3.12 or newer, IMO that is totally understandable.

When we finish the development(it's likely on the first half of 2024), Python 3.13 beta should be out.
